version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
  post_build:
    commands:
#      - aws s3 sync --delete dist s3://kinosabe-bucket
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
